### ISSUE TITLE
Cant even start the communication

### ISSUE THREAD

**Issue by huebrick** [u9n/dlms-cosem#74]
Hey, I am trying to build a testing tool for a meter from Mikroelektronika MEM600. Now I have the company tool which communicates with the meter over DLMS HDLC and I can read and write all the registers from there(obviously I have the auth information necessary to access the meter with the 01 management client). Now I want to build a quick tool to read and sometimes write registers of the meter but I cant even get it to start communicating. 

I am using the your HDLC example for testing(examples/dlms_with_hdlc_example.py) only modified the serial port to COM9 since that is where my optical probe is, and it is sending out the first message but the meter is not responding ( I know this meter works and communication works because it works with our software and I can verify that communication thru the optical and RS485 ports is set to DLMS(not mod E)).

Here is the output I get:
```
2024-01-22 13:00:11 [debug    ] HDLC state transitioned        new_state=AWAITING_CONNECTION old_state=NOT_CONNECTED
2024-01-22 13:00:11 [debug    ] Sending data                   data=bytearray(b'~\xa0\x08\x02#!\x93\xbdd~') transport=HdlcTransport(client_logical_address=16, server_logical_address=1, io=SerialIO(port_name='COM9', baud_rate=9600, timeout=10, serial_port=Serial<id=0x20eb7ea4070, open=True>(port='COM9', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=10, xonxoff=False, rtscts=False, dsrdtr=False)), server_physical_address=17, client_physical_address=None, extended_addressing=False, timeout=10, hdlc_connection=HdlcConnection(client_address=HdlcAddress(logical_address=1, physical_address=17, address_type='server', extended_addressing=False), server_address=HdlcAddress(logical_address=16, physical_address=None, address_type='client', extended_addressing=False), client_ssn=0, client_rsn=0, server_ssn=0, server_rsn=0, max_data_size=128, state=HdlcConnectionState(current_state=AWAITING_CONNECTION), buffer=bytearray(b''), buffer_search_position=1), _send_buffer=[], out_buffer=bytearray(b''), in_buffer=bytearray(b''))
2024-01-22 13:00:21 [debug    ] Received data                  data=b'' transport=HdlcTransport(client_logical_address=16, server_logical_address=1, io=SerialIO(port_name='COM9', baud_rate=9600, timeout=10, serial_port=Serial<id=0x20eb7ea4070, open=True>(port='COM9', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=10, xonxoff=False, rtscts=False, dsrdtr=False)), server_physical_address=17, client_physical_address=None, extended_addressing=False, timeout=10, hdlc_connection=HdlcConnection(client_address=HdlcAddress(logical_address=1, physical_address=17, address_type='server', extended_addressing=False), server_address=HdlcAddress(logical_address=16, physical_address=None, address_type='client', extended_addressing=False), client_ssn=0, client_rsn=0, server_ssn=0, server_rsn=0, max_data_size=128, state=HdlcConnectionState(current_state=AWAITING_CONNECTION), buffer=bytearray(b''), buffer_search_position=1), _send_buffer=[], out_buffer=bytearray(b''), in_buffer=bytearray(b''))

``` 

It just constantly keeps receiving "empty" messages.

I am not too familiar with HDLC and DLMS so I might be missing something.  I have tried different addresses, using the 16(client) address, I have tried different physical addresses.

And here is the communication that occurs between our software and the meter:

```
Open : COM9 (22/01/2024 13:18:40 )
TX - 
7E A0 0A 00 02 3A 71 03 53 90 01 7E ( +  41004 ms)  
RX - 
7E A0 0A 03 00 02 3A 71 1F 83 D6 7E ( +  437 ms)  
TX - 
7E A0 0A 00 02 3A 71 03 93 9C C7 7E ( +  226 ms)  
RX - 
7E A0 23 03 00 02 3A 71 73 53 5D 81 80 14 05 02 00 F2 06 02 00 F2 07 04 00 00 00 01 08 04 00 00 00 01 0C F7 7E ( +  196 ms)  
TX - 
7E A0 47 00 02 3A 71 03 10 46 98 E6 E6 00 60 36 A1 09 06 07 60 85 74 05 08 01 01 8A 02 07 80 8B 07 60 85 74 05 08 02 01 AC 0A 80 08 31 32 33 34 35 36 37 38 BE 10 04 0E 01 00 00 00 06 5F 1F 04 00 FF FF FF FF FF AD 1A 7E ( +  216 ms)  
RX - 
7E A0 3A 03 00 02 3A 71 30 3C D9 E6 E7 00 61 29 A1 09 06 07 60 85 74 05 08 01 01 A2 03 02 01 00 A3 05 A1 03 02 01 00 BE 10 04 0E 08 00 06 5F 1F 04 00 00 FA 1D 00 EF 00 07 D5 05 7E ( +  458 ms)  
TX - 
7E A0 1C 00 02 3A 71 03 32 1B 9E E6 E6 00 C0 01 C1 00 01 00 00 60 01 00 FF 02 00 89 A0 7E ( +  281 ms)  
RX - 
7E A0 1D 03 00 02 3A 71 52 B3 3D E6 E7 00 C4 01 C1 00 09 08 31 31 32 32 33 37 36 38 C5 46 7E ( +  232 ms)  
TX - 
7E A0 0A 00 02 3A 71 03 51 82 22 7E ( +  237 ms)  
RX - 
7E A0 0A 03 00 02 3A 71 51 F9 7D 7E ( +  170 ms)  
```

**Comment by Krolken** [comment]
Hi.

Using the `InformationFrame` class and parsing one of the resoponse from your program I get the following results:

```python
InformationFrame(
   destination_address=HdlcAddress(
       logical_address=1, 
       physical_address=None, 
       address_type='client', 
       extended_addressing=False), 
   source_address=HdlcAddress(l
      ogical_address=1, 
      physical_address=3768, 
      address_type='server', 
      extended_addressing=True), 
payload=b'\xe6\xe7\x00a)\xa1\t\x06\x07`\x85t\x05\x08\x01\x01\xa2\x03\x02\x01\x00\xa3\x05\xa1\x03\x02\x01\x00\xbe\x10\x04\x0e\x08\x00\x06_\x1f\x04\x00\x00\xfa\x1d\x00\xef\x00\x07', segmented=False, final=True, send_sequence_number=0, receive_sequence_number=1
)

```

So try with `physical_server_address=3768`

**Comment by huebrick** [comment]
Probably should of mantioned I tried that too and used that in my original post. But for the sake of testing here is the test with phy adr set to 3768

```
2024-01-22 14:52:20 [debug    ] HDLC state transitioned        new_state=AWAITING_CONNECTION old_state=NOT_CONNECTED
2024-01-22 14:52:20 [debug    ] Sending data                   data=bytearray(b'~\xa0\t\x02:q\x03\x937\x9c~') transport=HdlcTransport(client_logical_address=1, server_logical_address=1, io=SerialIO(port_name='COM9', baud_rate=9600, timeout=10, serial_port=Serial<id=0x1ace99b8190, open=True>(port='COM9', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=10, xonxoff=False, rtscts=False, dsrdtr=False)), server_physical_address=3768, client_physical_address=None, extended_addressing=False, timeout=10, hdlc_connection=HdlcConnection(client_address=HdlcAddress(logical_address=1, physical_address=3768, address_type='server', extended_addressing=False), server_address=HdlcAddress(logical_address=1, physical_address=None, address_type='client', extended_addressing=False), client_ssn=0, client_rsn=0, server_ssn=0, server_rsn=0, max_data_size=128, state=HdlcConnectionState(current_state=AWAITING_CONNECTION), buffer=bytearray(b''), buffer_search_position=1), _send_buffer=[], out_buffer=bytearray(b''), in_buffer=bytearray(b''))
2024-01-22 14:52:30 [debug    ] Received data                  data=b'' transport=HdlcTransport(client_logical_address=1, server_logical_address=1, io=SerialIO(port_name='COM9', baud_rate=9600, timeout=10, serial_port=Serial<id=0x1ace99b8190, open=True>(port='COM9', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=10, xonxoff=False, rtscts=False, dsrdtr=False)), server_physical_address=3768, client_physical_address=None, extended_addressing=False, timeout=10, hdlc_connection=HdlcConnection(client_address=HdlcAddress(logical_address=1, physical_address=3768, address_type='server', extended_addressing=False), server_address=HdlcAddress(logical_address=1, physical_address=None, address_type='client', extended_addressing=False), client_ssn=0, client_rsn=0, server_ssn=0, server_rsn=0, max_data_size=128, state=HdlcConnectionState(current_state=AWAITING_CONNECTION), buffer=bytearray(b''), buffer_search_position=1), _send_buffer=[], out_buffer=bytearray(b''), in_buffer=bytearray(b''))
2024-01-22 14:52:40 [debug    ] Received data                  data=b'' transport=HdlcTransport(client_logical_address=1, server_logical_address=1, io=SerialIO(port_name='COM9', baud_rate=9600, timeout=10, serial_port=Serial<id=0x1ace99b8190, open=True>(port='COM9', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=10, xonxoff=False, rtscts=False, dsrdtr=False)), server_physical_address=3768, client_physical_address=None, extended_addressing=False, timeout=10, hdlc_connection=HdlcConnection(client_address=HdlcAddress(logical_address=1, physical_address=3768, address_type='server', extended_addressing=False), server_address=HdlcAddress(logical_address=1, physical_address=None, address_type='client', extended_addressing=False), client_ssn=0, client_rsn=0, server_ssn=0, server_rsn=0, max_data_size=128, state=HdlcConnectionState(current_state=AWAITING_CONNECTION), buffer=bytearray(b''), buffer_search_position=1), _send_buffer=[], out_buffer=bytearray(b''), in_buffer=bytearray(b''))

```

**Comment by Krolken** [comment]
Try with `extended_addressing=True` too

**Comment by huebrick** [comment]
Hey thanks! That worked and I am now able to read registers from the meter.

Now I have encountered another issue which is kind of strange, so basically I can read everything from the meter no problem and out of nowhere is starts giving me this error.
```
Traceback (most recent call last):
  File "C:\Users\Mikroelektronika\PycharmProjects\HDLC test\ReadFREQ.py", line 63, in <module>
    with management_client.session() as client:
  File "C:\Users\Mikroelektronika\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Mikroelektronika\PycharmProjects\HDLC test\.venv\Lib\site-packages\dlms_cosem\client.py", line 68, in session
    self.associate()
  File "C:\Users\Mikroelektronika\PycharmProjects\HDLC test\.venv\Lib\site-packages\dlms_cosem\client.py", line 167, in associate
    raise exceptions.DlmsClientException(
dlms_cosem.exceptions.DlmsClientException: DLMS Exception: <StateException.SERVICE_NOT_ALLOWED: 1>:<ServiceException.OPERATION_NOT_POSSIBLE: 1>
``` 
And it goes away by itself too after some time, I was trying to trace it to a specific issue like restarting the PC, USB - RS485 adapter, the meter, trying other versions of python and so on. The way I was able to solve it is by getting another meter :) and this works for some time but then the same problem strikes again. Now the evidence would probably point to the meter being the problem but when I try it with our internal tool it works without a problem.

Here is the code im using, so this works just at some point it fails without an obvious cause:
```python
import logging
from functools import partial
from pprint import pprint

from dlms_cosem.protocol.xdlms.conformance import Conformance
from dlms_cosem.parsers import ProfileGenericBufferParser
from dlms_cosem.client import DlmsClient
from dlms_cosem import cosem, enumerations, utils, security
from dlms_cosem.io import SerialIO, HdlcTransport
from dlms_cosem.security import LowLevelSecurityAuthentication
from dlms_cosem import a_xdr, cosem, enumerations, utils
from dlms_cosem.a_xdr import AXdrDecoder
c = Conformance(
    general_protection=False,
    general_block_transfer=False,
    delta_value_encoding=False,
    attribute_0_supported_with_set=False,
    priority_management_supported=False,
    attribute_0_supported_with_get=False,
    block_transfer_with_get_or_read=True,
    block_transfer_with_set_or_write=True,
    block_transfer_with_action=True,
    multiple_references=True,
    data_notification=False,
    access=True,
    get=True,
    set=True,
    selective_access=True,
    event_notification=False,
    action=True,
)

usb_port: str = "COM4"


serial_io = SerialIO(
    port_name=usb_port,
    baud_rate=9600,
    timeout=500,
)



management_hdlc_transport = HdlcTransport(
    client_logical_address=1,
    server_logical_address=1,
    server_physical_address=2836,
    extended_addressing=True,
    io=serial_io,
)

management_client = DlmsClient(
    transport=management_hdlc_transport,
    authentication=LowLevelSecurityAuthentication(secret=b"12341234"),
)

CURRENT_ASSOCIATION_OBJECTS = cosem.CosemAttribute(
    interface=enumerations.CosemInterface.REGISTER,
    instance=cosem.Obis(1, 0, 1, 8, 0, 255),
    attribute=2,
)

with management_client.session() as client:
    profile = client.get(
        CURRENT_ASSOCIATION_OBJECTS,
    )
    result = utils.parse_as_dlms_data(profile)
print(result)
``` 

As you can see im using a different phy adrs then before, I have switched between few meters trying to get to the bottom of this :)

As I was writing this one of the meters decided to start working again so at this point I am very confused and am starting to suspect the meters being in some way the problem. 

Also could you point me in the right direction on how would I go about writing to the registers?

**Comment by huebrick** [comment]
I managed to get it working, but for the sake of those going down the same rabbit hole as me here is what was happening and how I solved it. This problem is caused when you have an error before the  ``` release_association() ``` which causes the meter to think you are still associated and it doesn't allow new associations before the old one is closed. 
So I solved this in a very hacky way, by basically sending this ``` 7E A0 0A 00 02 FE FD 41 53 3C 94 7E ``` over serial before calling``` connect() ``` which I think tells the meter to release all associations. 

Thanks again for the help, just the fact that this is open source is amazing and is probably make learning DLMS HDLC a lot easier for me.

**Comment by Krolken** [comment]
I think we could improve the session handling with a try-catch statement in the contextmanager.
So if we would get a DlmsClientError we would try to release the association.

something like:

```python

 @contextlib.contextmanager
    def session(self) -> "DlmsClient":
        
        self.connect()
        self.associate()
        try:
             yield self
        catch DlmsClientError:
            if settings.release_association_on_error:
                self.release_association()
                self.disconnect()

        self.release_association()
        self.disconnect()

```
